### ISSUE TITLE
WSSSPE4 report: Verifying best practices & metrics for sustainable research software

### ISSUE THREAD

**Issue by kyleniemeyer** [WSSSPE/meetings#135]
In Section 8, "Verifying best practices & metrics for sustainable research software", the participant list (Sec. 8.1.1) has four people (Ray, August, Jonah, and Lorraine), but section 8.1.4 ("Relevant people and resources") adds Peter Elmer and Hans Fangohr. Should those be included in the participants list?

I think @rayi113 (Ray) wrote this section, so perhaps my question should be directed at him? Otherwise, maybe @ljhwang or @Yurlungur would know?

**Comment by rayi113** [comment]
This was intentional and is meant to be accurate as-is.  The first four people (Ray, August, Jonah, and Lorraine) were the active people in the sessions sitting at the table discussing and planning.  The two others (Peter Elmer and Hans Fangohr) stopped by during the walk-around and reviews and asked to be included in future work without actively participating in the initial session, if that is okay to structure it this way.

**Comment by kyleniemeyer** [comment]
Ah ok, got it. If it's ok with you, I may clarify that slightly, mainly to eliminate the repeated names & emails from the participant list.

**Comment by rayi113** [comment]
Okay with me, thanks very much.

**Comment by danielskatz** [comment]
@kyleniemeyer - did you do this?  (i.e. can we close the issue?)

**Comment by danielskatz** [comment]
@kyleniemeyer If this still needs to be done, can you do it in the next couple of days?

**Comment by kyleniemeyer** [comment]
@danielskatz ok will do it now

**Comment by kyleniemeyer** [comment]
Alright, done via 45b7cc88427862415e07517ad8a87748678bcc2e

**Comment by rayi113** [comment]
Thanks.

**Comment by danielskatz** [comment]
thanks.
